default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASS", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  sslmode: <%= ENV.fetch("DB_SSLMODE", "require") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  gssencmode: disable 
  prefer_ipv4: true  
development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "admin_dashboard_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "test_db") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME") %>
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASS") %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME") %>_cable
    migrations_paths: db/cable_migrate